// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    autonomous_fund
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        withdraw => withdraw
        submitProposal => submit_proposal
        vote => vote
        finalizeVoting => finalize_voting
        executeProposal => execute_proposal
        cancelProposal => cancel_proposal
        expireProposal => expire_proposal
        getProposal => get_proposal
        getProposals => get_proposals
        getActiveProposals => get_active_proposals
        getFundStats => get_fund_stats
        getSharePrice => get_share_price
        getMembers => get_members
        getMemberShares => get_member_shares
        getEpochSpent => get_epoch_spent
        getVoteRecords => get_vote_records
        hasAgentVoted => has_agent_voted
        getContractConfig => get_contract_config
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
